### ISSUE TITLE
Move from staging to main branch

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#1081]
Now we've started doing releases we think it's time to move from the staging branch to main branch. We want to try and do this with minimal disruption, so our suggested approach is. First delete the `main` branch and then rename `staging` to `main`. This should automatically move all the PRs over, but there are still some things people will need to do
- Update the references in code to the staging branch - this can be prepped ahead of time
- Update people's local dev environments (and forks?) - each developer will need to do this themselves by running something like:
  ```
  git branch -m staging main
  git fetch origin
  git branch -u origin/main main
  git remote set-head origin -a
  ```
- Update downstream projects that reference the staging branch - this will need maintainers of those to sync with the updates

Because of these changes we should give people notice and a chance to request delays to get organised

### Task list
- [x] Post of slack to notify people that we plan to do this and request any feedback and pick a date
- [x] Create a PR changing the `staging` code references to `main`: https://github.com/confidential-containers/cloud-api-adaptor/pull/1097
- On the date picked:
  - [x] Remind people that the switch is happening
  - [x] Delete the `main` branch
  - [ ] Rename the `staging` branch to `main`
  - [ ] Merge the PR that changes the `staging` code references to `main`
  - [ ] Message people to let them know the change happened and remind them to update their local dev environments and downstream projects.
