### ISSUE TITLE
Add creation of the IS SSH key to the cluster Terraform template in x86 peer pod demo

### ISSUE THREAD

**Issue by jtumber-ibm** [confidential-containers/cloud-api-adaptor#24]
## Description
The public cloud-api-adaptor repo contains a [Terraform template](https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/ibmcloud/terraform/cluster) for setting up the VSI instances for the demo environment for running the cloud api adaptor and peer pods demo. This template requires a public SSH to be added to the region the VSI instances will run in in IBM Cloud, which currently has to be done manually in IBM Cloud outside of Terraform.

To get the full one-click experience when setting up the demo environment Terraform should create this SSH key as well. You'd do this by making Terraform create an instance of the `ibm_is_ssh_key` [resource](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_ssh_key)

## Task List
- [ ] Read the docs for the VPC infrastructure SSH key in the IBM Cloud Terraform provider, https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/resources/is_ssh_key, to understand how to create an instance of this resource and how to access the data values associated with this resource once it has been created
- [ ] Update the Terraform template in `ibmcloud/terraform/cluster` so that the template creates a new SSH key instance rather than using a pre-existing one
- [ ] Add the name of the SSH key to the template's `locals` (e.g., construct it using `var.cluster_name` like the other `locals` for the template)
- [ ] Make the creation of the instance template in this Terraform template use the newly created SSH key resource
- [ ] Add a new variable for the SSH public key value to the Terraform template and remove the SSH key name variables
- [ ] Test the updated Terraform template for the create the Kubernetes cluster - you will need to run the `ibmcloud/terraform/common` Terraform template before `ibmcloud/terraform/cluster` to create the VPC, subnets and security groups etc
- [ ] Update the README.md file in `ibmcloud/` to reflect the SSH key is added to IBM Cloud automatically and explain how to add your public SSH key to the Terraform template as an input variable

## Security Considerations
It is the public SSH key that should be added to `terraform.tfvars`, not the private key. As this is a public key there would be not bad security implications of disclosing this public key, but we want to make sure we do not accidentally write the private key to a file then carelessly upload it to source control.

## Performance Considerations
None

## Acceptance Criteria

**Given** I want a one-click experience when creating the Kubernetes cluster for the peer pod demo environment 
**When** The `ibmcloud/terraform/cluster` template is applied
**Then** Applying the template creates the SSH key object using the public SSH key variable input to the template, which the VSIs for the demo environment then use
