### ISSUE TITLE
CI: add a pipeline to test the webhook

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/cloud-api-adaptor#291]
The webhook is a stand-alone project hosted alongside the CAA repository on the [webhook]( https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/webhook) directory.

It is not tied to any specific cloud provider and can be tested in isolation, i.e., you don't need a virtual private cloud nor the whole CAA stack installed, but just a running k8s cluster. So this item is about adding a CI job to test changes made to the webhook sources solely.

**Use case**: As a developer that submitted a pull request changing the webhook, I want to have my changes tested to ensure it doesn't introduce regressions.

## Task list

- [ ]  Investigate if a Github action over the default runner is enough for implementing the pipeline
- [ ] Create tests. E.g., start a pod and check it changed the resources as expected
- [ ] Implement the pipeline properly saying

Cc @bpradipt
