### ISSUE TITLE
As a user I want to create a Kubernetes cluster using the demo instructions on MacOS

### ISSUE THREAD

**Issue by Jonah-F** [confidential-containers/cloud-api-adaptor#34]
## Description
Currently when you run the `terraform/cluster` template in the cloud-api-adapter demo on MacOS you receive an error after the containerd dependency in the Ansible playbook times out. 

@mattarnoatibm kindly informed me they had the same issue running from their system when running the demo steps. Matt has identified a mitigation for this which is to include the `-f` parameter in `terraform/cluster/scripts/keygen.sh` line 71, which would look like this:

```
ssh-copy-id -f "${opts[@]}"  ...
```
this fixes the error encountered when running the Terraform template from a MacOS system.

However, including the above mitigation could have knock-on effects for other systems. So the change we actually want here is to have the `keygen.sh` script check the operating system of the user, and choose the best option for them. This could be done using an if-else. 

By identifying the operating system of the user running the script, we fix this issue for MacOS systems, and prevent side effects by forcing the `ssh-copy-id` to copy the key if there is something wrong.

## Task List
- [ ] Make changes to `cluster/scripts/keygen.sh` near line 71 to include an if-else that compares operating systems so the `ssh-copy-id` command is executed either with the `-f` parameter for MacOS or, as it is now, without.
- [ ] Test fix on MacOS and show results.
- [ ] Test fix on Ubuntu 18.04 - 20.04
- [ ] Make a PR for this change. This story is not done until the PR is approved & merged.

## Performance Considerations
Nothing comes to mind.

## Security Considerations
Nothing comes to mind.

## Acceptance Criteria
**Given** I want to create a new Kubernetes cluster
**When** I run the demo steps to create one using a system on MacOS
**Then** I have a new, working Kubernetes cluster as expected

**Comment by ariel-adam** [comment]
@Jonah-F is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by mattarnoatibm** [comment]
Hi Ariel.

This issue is still relevant for users running the `terraform/cluster` configuration for setting up the peer pods / cloud api adaptor demo for IBM Cloud on MacOS.

I think it could be completed for mid-November as long as we don't change how the `keygen.sh` works for people running demo for IBM Cloud setup on non-MacOS workstations.

**Comment by ariel-adam** [comment]
@mattarnoatibm just wanted to check you still think this can converge for release V0.3.0 (January 15th freeze0

**Comment by mattarnoatibm** [comment]
Hi @ariel-adam , yes, this work should be complete following merging commit [f489244](https://github.com/confidential-containers/cloud-api-adaptor/commit/f489244076dae8cf42f0c0a510054a024683f23b) into the staging branch.
